spring.application.name=luxury

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/luxury}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1626}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
seguridad.jwt.secreto=${JWT_SECRETO:8j4L/f9V2kE7xP3uQ1wR6yT5mN0bZ8A4XcV7iG2qM5=}
seguridad.jwt.expiracionMinutos=1440
